FROM node:22-alpine
WORKDIR /src

# 패키지 파일들 복사
COPY package*.json ./
COPY prisma ./prisma/

# 의존성 설치
RUN npm install

# 프로젝트 파일들 복사
# COPY . .

# 핫리로드를 위한 환경 변수 설정
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

# 개발 서버 실행 (핫리로드 활성화)
CMD ["npm", "run", "dev"]