
import { Noto_Sans_KR } from 'next/font/google';

import AuthProvider from '@/components/providers/AuthProvider';
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils";

// 폰트 설정
const notoSansKr = Noto_Sans_KR({
  // preload: true, // (선택) 미리 로드할지 여부
  subsets: ['latin'], // 또는 'korean' (보통 Next.js가 알아서 최적화해줌)
  weight: ['100', '400', '700'], // 사용할 폰트 두께
  variable: '--font-noto-sans-kr', // CSS 변수 이름 지정
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="light layout-full">
      <body
        suppressHydrationWarning={true}
        className={cn(
          "antialiased font-sans",
          geistSans.variable, 
          geistMono.variable, 
          notoSansKr.variable
        )}
      >
        <AuthProvider>
          <div className="max-w-[1280px] mx-auto">
            <Header />
            <main className="min-h-[calc(100vh_-_112px)] p-8 pb-20 sm:py-10 sm:px-20 w-full flex flex-col">
              {children}
            </main>
            <Toaster />
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
